enable-magisk-update = true

[YT-ReVanced]
build-mode = "module"
excluded-patches = "'Theme'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music-Revanced]
build-mode = "module"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[YT-Extended]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
patches-version = "v4.10.2-dev.2"
integrations-version = "v1.11.2-dev.2"
included-patches = "'Visual preferences icons'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme'"
build-mode = "module"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music-Extended]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
patches-version = "v4.10.2-dev.2"
integrations-version = "v1.11.2-dev.2"
included-patches = "'Hide player overlay filter'"
excluded-patches = "'Amoled' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
build-mode = "module*
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
